# Generated by Django 3.2.16 on 2022-11-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Featured_image',
            new_name='featured_image',
        ),
    ]
