# Generated by Django 3.2.16 on 2022-12-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4blog', '0009_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
